### PR TITLE
pip may installed the MKL libraries in the user folder on Linux

### PR DESCRIPTION
**Pull request by msrocka**
The MKL library cannot be found when it is installed in the user directory via pip on Linux. This pull request hopefully fixes this by also searching this location for the library.

### CODE REVIEW

**Comment by haasad** [comment]
Thanks for the PR @msrocka what Linux flavor are you using?

**Comment by msrocka** [comment]
Ah, true: Ubuntu 20.04.5 LTS, Python 3.11.0, installed it globally, not in a virtual environment via pip

**Comment by haasad** [comment]
Hi Michael,

thanks again making this PR, I expanded on your changes in #47 to make it work for all operating systems. I already made a new release and I hope with pypardiso 0.4.2 your issue is fixed.

Cheers,
Adrian

**Comment by msrocka** [comment]
Many thanks Adrian! Yes, version 0.4.2 fixes the issue for me, fantastic.

**Pull request closed without merging**
